### ISSUE TITLE
Lock In from CLI doesn't work

### ISSUE THREAD

**Issue by cs12ag** [benleb/surepy#12]
https://github.com/benleb/surepy/blob/456d9bf43429fc591489e933dd8a687198a37e01/surepy/cli.py#L392

Howdy Ben! I think you're missing a line when attempting to lock the cats inside using the CLI. I suspect you need to add
`lock_control = flap.lock_in`
immediately before/after the line I've linked to above.

**Comment by benleb** [comment]
ah thanks!!
