### ISSUE TITLE
Interested in mentored sprints?

### ISSUE THREAD

**Issue by lgfunderburk** [benleb/surepy#18]
Hi Ben, 

Came across your surepy repository and I am wondering if you'd be interested in being part of a mentored sprints event series [(here for info)](https://www.meetup.com/PyLadies-Vancouver/events/276577647/) sometime in April. 

How does it work? We work together to identify improvements and issues people can work on, and on the day of the event we get together and tackle issues. 

We share your project on social media, and advertise you are seeking sponsors. 

Let me know if this is something you'd be interested in. 

Laura from Vancouver PyLadies
https://twitter.com/pyladiesvan
https://twitter.com/LGFunderburk

**Comment by benleb** [comment]
Sounds cool! Will contact you on twitter :)
