### ISSUE TITLE
Add feeder data on integration

### ISSUE THREAD

**Issue by blair287** [benleb/surepy#2]
Hello,

Any chance of adding some more data from the feeder other than just battery life I have found the data that would be helpfull to be added i can supply access to an account with feeders if required.

**Comment by B-Hartley** [comment]
Have you managed to get anywhere with feeder info yet. Would be great to know when my cats are eating (in home assitant)

Thanks.

**Comment by crgreenwood** [comment]
Happy to assist with testing any enhancements here as I have a feeder, and a good level of familiarity with the with integration having used it since it was a custom component had to hack it when we had the API timeout issue.

**Comment by B-Hartley** [comment]
I’d be happy to be involved with testing too.

**Comment by blair287** [comment]
I'd be happy to lend access to an account of it would help.

Data that would be useful would probably be:

Last ate
Food remaining
Weight bowls set to eg 100g for left bowl then you could with template work out food left as a percentage etc.
If 1 or split bowls in use.

**Comment by macgirlsweden** [comment]
I would love to see more data to be able to do proper graphs and reporting of our cats eating behaviour.

**Comment by benleb** [comment]
Hey, basic feeder data is available via surepy now.

Regarding the integration I suggest to ask for this in the home assistant repo or community or something as this not really belongs in here. The code of the integration is not in this repo and to keep the things clean, Issue regarding the integration should also done somewhere else :) Thanks!

**Comment by B-Hartley** [comment]
That's great, thank you
