### ISSUE TITLE
Longer tokens are not supported

### ISSUE THREAD

**Issue by botterli** [benleb/surepy#203]
Hello, 

I fetched a new token today, and it was 491 characters long. This is longer than `token_seems_valid()` accepts, so it was rejected. After editing the function to allow tokens of length up to 500 I was able to authenticate and use surepy as normal. I would add a PR, but I have no idea what is considered an acceptable length.

Thanks for making this module!

**Comment by MechEng70** [comment]
@botterli did you change line 71 of client.py?

**Comment by botterli** [comment]
@MechEng70 Yes, that is correct

**Comment by MechEng70** [comment]
@botterli How did you edit that file?  in my custom components, I have the sureha and not the surepy.

**Comment by botterli** [comment]
I simply replaced ‎448 with 500.

**Comment by MechEng70** [comment]
I am having issues finding the file.  Do you have this as a custom component?  If not, did you SSH into your HA and locate the file?

**Comment by botterli** [comment]
I'm not using HA, but my custom system to integrate this module. I don't know anything about HA, I'm afraid

**Comment by benleb** [comment]
sorry - limit removed 👍  https://github.com/benleb/surepy/commit/980678524efe57ae7935417dd11578b94751afa4

**Comment by MechEng70** [comment]
@benleb I realize that this closed (and thank you for fixing it).  Tactical question, how does this get pulling into SureHA on HA?  Do we need to wait for the latest update?

**Comment by benleb** [comment]
I will do a new release probably tomorrow (and maybe merge some other MRs before 👍 ) :)
