### ISSUE TITLE
Create usage example

### ISSUE THREAD

**Issue by jonootto** [benleb/surepy#21]
Would it be possible to generate a usage example as part of this project of how to use this within another python script? How to retrieve the state of a pet door for example would be most helpful.

There are only examples/docs for using CLI at present.

**Comment by benleb** [comment]
Currently there is no real doc but for a rough idea, you can check the [code of the CLI](https://github.com/benleb/surepy/blob/dev/surepy/surecli/__init__.py) script :)
I pushed the upcoming release version to the dev branch yesterday, please use this as example and not the master (as the dev contains breaking changes and will be released in the next days)

**Comment by jonootto** [comment]
That's perfect! Thanks very much.
