### ISSUE TITLE
ValueError in _generate_device_id

### ISSUE THREAD

**Issue by epenet** [benleb/surepy#3]
Hi,

Sometimes, it seems that _generate_device_id raises a ValueError exception (see https://github.com/home-assistant/core/pull/40926/checks?check_run_id=1192119389)

```
>       mac_dec = int(random_bytes.replace(":", "").replace("-", ""), 16)
E       ValueError: invalid literal for int() with base 16: 'd4 d49085535'
```

This could be resolved by replacing spaces with "0"

**Comment by epenet** [comment]
Can you push an update to https://pypi.org/project/surepy/ ?

**Comment by benleb** [comment]
https://pypi.org/project/surepy/#history :)
