### ISSUE TITLE
Add scripts/service calls for Curfew, Pet Location, Exit Permissions for Flaps

### ISSUE THREAD

**Issue by axa4953** [benleb/surepy#42]
The updated version of the repo allows user to configure service calls to set the lock_state of the pet door products.

On the official app its also possible to:
- Set Pet status to inside/outside manually -> parameter "where", options (0,1,2)
- Set up-to 4 curfews that restrict exit of pets towards outside (but they can re-enter) -> see picture for examples
- Set pets as "inside only" pets, without access to the outside (but they can re-enter) 

It would be great if these options can be executed via service calls in the future, via HA

![image](https://user-images.githubusercontent.com/34874748/117595244-a7dc5900-b183-11eb-8630-db8bad6f8933.png)
![image](https://user-images.githubusercontent.com/34874748/117595391-0acdf000-b184-11eb-800f-67e7df6ca26f.png)

**Comment by Ashitaka57** [comment]
- Set Pet status to inside/outside manually -> parameter "where", options (0,1,2)
This is already implemented via this function  async def set_pet_location(self, pet_id: int, location: Location) located in client.py

-  Set pets as "inside only" pets, without access to the outside (but they can re-enter)
I already asked for that feature, it would be great to have it indeed.
See Issue https://github.com/benleb/surepy/issues/13
